kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}
  {{- if .Values.svcAnnotations }}
  annotations:
  {{- range $key, $value := .Values.svcAnnotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
  - name: kubernator
    protocol: TCP
    port: 80
    targetPort: 80
  - name: kubectl
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
